### ISSUE TITLE
Doesn't check for stack overflow

### ISSUE THREAD

**Issue by zeckalpha** [munificent/wren#153]
~~~
> class Oops { static test { test }}
> Oops.test
Segmentation fault: 11
~~~

**Comment by munificent** [comment]
Yeah, this is just a class stack overflow. You're calling your own method recursively.

Wren should check for this and handle it gracefully instead of crashing, though. I'll edit the bug title to mention that if it's OK with you. :)

**Comment by zeckalpha** [comment]
No problem.

**Comment by zeckalpha** [comment]
This one still seems to occur.

**Comment by munificent** [comment]
Yup. There's basically two things we need to do here:

1. Have `ObjFn` store the maximum number of slots it needs. When a function is called, it checks to see if there's enough room for the stack.
2. Decide how we want to handle that. We could either try to grow the stack dynamically or just fail with a runtime error.

I'm leaning towards the first because it would let us make stacks initially much smaller, which makes it cheaper to have lots of fibers. Doing this will have... interesting... consequences for performance, though. It's definitely something we need to fix at some point, though.

**Comment by RallyTronics** [comment]
As a firmware developer who would like to implement Wren on a micro-controller with limited resources, dynamic stack growth scares me.  I would much prefer a runtime error.

**Comment by munificent** [comment]
Ah, thank you for that perspective, @RallyTronics! Maybe the right solution is to:

1. Start with having a runtime check on overflow.
2. Possibly eventually add dynamic growth but provide a `#define` to let users choose which behavior they want.

I think #2 can be useful for a lot of users because it lets us make the initial stack size *very* small (since the minority of fibers that need it will just grows dynamically when they have to). That, in turn, makes it easier to support a very large number of concurrent fibers, which is something I'd like.

**Comment by RallyTronics** [comment]
I think #2 would be perfect.  It would be a great option to have.

**Comment by munificent** [comment]
OK, I have dynamic growth working now as of e7d10218db3cee5222835edeaa38e5ca0a81373b. I think that's the right default behavior because it lets fibers start with very small small stacks, which saves a lot of memory and allows each fiber to adapt its stack size to what it actually needs.

We could also add a limit to the stack size, but it may be simpler to just control that at the application level by not allowing code that recurses too deeply.
