### ISSUE TITLE
Cleaner function syntax?

### ISSUE THREAD

**Issue by zeckalpha** [munificent/wren#158]
I had an idea about cleaning up the function syntax. Instead of having function-like classes expose a `call` method, they can use their constructor. If paired with removing the the `new` keyword, this makes calling a function simpler.

~~~ dart
class Identity {
  new(x) { return x }
}

var x = Identity(1)
~~~

**Comment by munificent** [comment]
Hmm. I think that would work in cases where the name is capitalized, but it falls down otherwise because then `name(arg)` gets compiled as `this.name(arg)`. I actually wrote up a reply to someone else about why Wren uses `call` here. I need to add it to the FAQ. Until then:

---

Consider:

```dart
class Foo {
  a { _a }
  a(arg) { IO.print("method) }

  new {
    _a = new Fn {|arg| IO.print("fn") }
    a("arg") // <--
  }
}
```

How do we interpret `a("arg")`. Is it:

1. Invoke the `a` getter, get the result (a function) and then call that.
2. Invoke the `a` method, passing in the argument.

The obvious answer is 2. But that means if you *do* want to invoke a getter and then invoke the result of that, you would have to parenthesize:

```dart
class Foo {
  a { _a }
  a(arg) { IO.print("method) }

  new {
    _a = new Fn {|arg| IO.print("fn") }
    (a)("arg") // <--
  }
}
```

But if the function is stored in a local variable, you don't:

```dart
var a = new Fn {|arg| IO.print("fn") }
a("arg")
```

Every language has to figure out how to resolve this conundrum. C++, Java, and C# rely on static typing to determine if `a(arg)` is a method call or a getter call and then an invocation on the result.

Python always treats it like the latter and then treats all method as basically properties that return "bound functions". But that sacrifices overloading by arity.

Ruby and Smalltalk, like Wren, don't use "unnamed" syntax for calling functions and instead make function invocation a named method. While Wren doesn't look much like either of those languages, once you scrape the curly braces and C syntax off, it's actually quite close to them.

I think if we really wanted to, we could get rid of `.call` but I think it keeps things simpler to require it. It also fits in that Wren is mostly method-based anyway. You rarely have "top level" functions that you invoke like you would have in C. So the extra `.call` usually only shows up in higher-order functions and in there, it looks OK to me.

Having function calls be a normal named method also makes it easier to define your own classes that work like functions. Just define a method named "call" and you can pass it to `.map()`, `.where()` or anything else that expects a "real" function. If we had direct function-call like syntax, we'd also have to add operator overloading for it to support this.

---

There's also some difficulty under the hood with removing the `new` keyword. Object creation happens in two steps—allocation and construction—and `new` helps the compiler know when to kick off that process. Probably not insurmountable, but it's part of the reason there's a `new` keyword.

Of course, the other reason there's a `new` keyword is because it's familiar to people coming from C++, Java, C#, JavaScript, et. al.

**Comment by zeckalpha** [comment]
Yes. I recalled that previous discussion but wasn't able to find it.

**Comment by bytemaster** [comment]
I suppose this could be implemented as:

```
a.(args)  
```

The extra '.' indicates the dereference similar to (a)(args).

**Comment by lluchs** [comment]
Yes. I actually [implemented that](https://github.com/munificent/wren/pull/302) and there was some discussion about it on the mailing list [here](https://groups.google.com/forum/#!topic/wren-lang/61C6aeIK3sc) and [here](https://groups.google.com/forum/#!topic/wren-lang/mdPbSiuWwBM).
