### ISSUE TITLE
Random numbers

### ISSUE THREAD

**Issue by jkleiser** [munificent/wren#170]
I would like the Num class to have 'rand' and 'seed' static methods.
I like the Wren language very much. ;-)

**Comment by MarcoLizza** [comment]
I'm working on those (and others) `Num` class methods.

I will submit the pull request in the very next days.

**Comment by munificent** [comment]
Since random number generation implies some (hidden) mutable state, this may be a case where a separate class is a better fit. Something roughly like:

```dart
class Random {
  new { /* Automatically seed... */ }
  new(seed) { ... }

  // Methods for getting random values...
}
```

That way users have clear control over where that state lives, can maintain separate PRNGS, etc.

> I'm working on those (and others) Num class methods.

You can always send those out as individual pull requests. Incremental changes generally make everyone's life easier. :)

**Comment by MarcoLizza** [comment]
> Since random number generation implies some (hidden) mutable state, this may be a case where a separate class is a better fit.

I started and added the PRNG feature to Wren some weeks ago, if you recall, but left incomplete (due to other priorities).

Now that we have modules, I was thinking just the same that having a separate PRNG as class instances would be a better choice.

First of all, it would be a first step in trying the module support itself. Moreover, it would be (eventually?) part of the standard Wren-lib... :dancer: 

> You can always send those out as individual pull requests. Incremental changes generally make everyone's life easier. :)

Yep, I will send them and leave the PRNG support as a module class, then. :wink:

**Comment by MarcoLizza** [comment]
I guess this one can be closed, now that we have module support and bitwise operations.

A class like this is enough to implement a fast and easy PRNG
```dart
class Random {

  new {
    _x = 123456789
    _y = 362436069
    _z = 521288629
    _w = 88675123
  }

  new(seed) {
    _x = seed
    _y = 362436069
    _z = 521288629
    _w = 88675123
  }

  next {
    var t = _x ^ (_x << 11)
    _x = _y
    _y = _z
    _z = _w
    _w = _w ^ (_w >> 19) ^ t ^ (t >> 8)
    return _w / 4294967296
  }

}
```

**Comment by munificent** [comment]
Yeah, probably. I certainly want to keep the core lib minimal, and RNGs are something that we can exclude from core.

At the same time, it's really useful to have one widely available. Right now, Wren has no concept of a "standard library", meaning a module that you have to import to use but that physically ships with Wren. Everything in core is implicitly imported.

I'm not sure if I even want to have such a concept because I worry it's a slippery slope to having lots of standard libraries. But, at the same time, a nice PRNG is really useful to a lot of programs, especially given that Wren has an eye towards games.

I'll leave this open for now, but I don't intend to take any action on it until other stuff is further along.

**Comment by MarcoLizza** [comment]
> But, at the same time, a nice PRNG is really useful to a lot of programs, especially given that Wren has an eye towards games.

Yep, in fact that's the reason why I started working on adding a PRNG to Wren some weeks ago.

However, the random number generator can be easily provided in some way thru' the embedding API by the host that is running Wren's VM (and you will use that API when developing a game or such).

Also, providing a PRNG raises another question: which one? A simple linear congruential generator could be enough for some but too simple for others. Implementing a "complex" generator would easily go against Wren's philosophy to keep everything reasonably simple.

I feel it won't be worth the effort, in the end. It's better to leave the pleasure to implement it to anyone who needs it.

Maybe we could create a snippets library, over time.

**Comment by munificent** [comment]
> However, the random number generator can be easily provided in some way thru' the embedding API by the host that is running the Wren's VM (and you will use that API when developing a game or such).

True!

> Also, providing a PRNG raises another question: which one?

Yeah, excellent point.

**Comment by gsmaverick** [comment]
This is probably something that would make sense to include in [wren-io](https://github.com/zeckalpha/wren-io).
cc @zeckalpha
