### ISSUE TITLE
wrenrc file to configure interpreter

### ISSUE THREAD

**Issue by hachibu** [munificent/wren#190]
I came across this todo in src/main.c.

#define MAX_LINE_LENGTH 1024 // TODO: Something less arbitrary.

And I thought it might be nice to have a wrenrc file to configure the interpreter. What do you think?

**Comment by gsmaverick** [comment]
I'd be partial to using a command line argument; that way we don't have the problem of needing to read and parse another file when starting up the interpreter.

**Comment by hachibu** [comment]
That makes a lot of sense to me, especially since Wren is supposed to be small and fast. I'd be in favor of a command line approach to this problem.

**Comment by MarcoLizza** [comment]
To be honest 1024 characters is fair enough for the REPL line buffer. I second the command line parameter, in case.

**Comment by munificent** [comment]
I think for the REPL specifically, the right thing to do is have it grow dynamically. I've got some half-formed plans to give the REPL some real love that should address this (mainly by moving most of the REPL into Wren itself).

For configuration in general, I think most things fall into one of two buckets:

* **Compile time flags.** These are things like `WREN_NAN_TAGGING`, `WREN_COMPUTED_GOTO`, etc. Stuff where the host application wants to control it and where setting it affects the compiled code of Wren itself.

* **Host configuration.** These are the fields you pass in using the `WrenConfiguration` struct when you create a new VM. Stuff like GC parameters, and callbacks Wren needs to talk to the embedder.

For Wren itself—the core Wren implementation—I don't plan to go beyond that. Wren isn't really a general purpose language right now, just an embedded scripting language.

I am super excited to *also* have Wren be usable as a general purpose language by wrapping it in a host embedder that adds a bunch of IO APIs, similar to what node.js does for JS. @zeckalpha is looking at that. If I had ten more hours each day, I would be hacking on that like you wouldn't believe.

But, since I don't, I figure the best use of my time is to focus on just Wren-as-an-embedded-language, since it keeps the scope much smaller. Given that, I don't think we'll need anything like configuration files.

I do totally agree the hard-coded constant for the REPL is a hack, though. :)

**Comment by hachibu** [comment]
Ah cool, this makes a lot of sense to me now. Thanks for the detailed response!
