### ISSUE TITLE
Embedding API: accessing VM symbols

### ISSUE THREAD

**Issue by MarcoLizza** [munificent/wren#193]
Let's say you are using Wren as simple configuration scripting language (as someone does with other scripting languages).

*( please note that I'm not arguing that using a scripting languages this way is something I wan't to do, nor I second )*

How can you access the Wren-side symbols, such as the variable that holds (let's say) the rendering viewport width/height?

I think that, out of the above example, there can be occasions where accessing a VM symbol can be useful.

*( either way, you can definire a static method to pass the single value to the VM host )*

**Comment by munificent** [comment]
This is a good question. It's something Lua was specifically designed to support. With Wren, I've mostly been thinking of it as an imperative scripting language, but I don't think wanting to be usable for configuration is a bad idea either. Most of the internal bookkeeping data needed for this is there, it's mostly a question of exposing it in the embedding API.

**Comment by MarcoLizza** [comment]
I really like that Wren is mostly imperative in nature but the host itself may need to access the VM variables.

For example, looking a symbol up can also serve as a way to get a reference to the instance whose method you want to call (although that's not the preferred way to achieve this, in my opinion).

As for the API, could we tentatively write down some specifications?

It would be better to have
* a single symbol-lookup (`wrenLookupSymbol()`) function and several accessors for each integral type (`wrenGetAsString()`, `wrenGetAsNumber()`, and so on), or
* several accessors that combine the above?

Perhaps having a separate lookup function could be useful in other cases.

**Comment by munificent** [comment]
It would probably be separate functions per-type since Wren doesn't expose any way to get a reference to a generic object (and likely won't since it avoids leaking VM and GC internals). That's how we handle arguments in foreign functions, so it would probably be the same for accessing module variables.

**Comment by MarcoLizza** [comment]
Fine. That sound appropriate.

**Comment by munificent** [comment]
You can do this now using the C API. It's a little convoluted because it involves going through the C API's slot stack, but that helps keep the API simple. If you want to access a top-level variable's value from C, first you load it into a slot:

```
// Make sure there we have a stack with a slot in it.
wrenEnsureSlots(vm, 1);

// Load the variable into the slot.
wrenGetVariable(vm, "module", "SomeVariable", 0);
```

Then, based on its type, you can get the value out. Say it's a number:

```
double value = wrenGetSlotDouble(vm, 0);
```

There are `wrenGetSlot___()` functions for all of the various value types.
