### ISSUE TITLE
Embedding API: calling function/method

### ISSUE THREAD

**Issue by MarcoLizza** [munificent/wren#194]
When integrating a scripting language into a (game) engine there are chances you'll end up with an event-based approach.

On precise times, the host need to call (callback) functions and methods residing in the VM.

Currently, the only way to do this is to dynamically generate the script statement and interpret it. This is easy and versatile *but* has two major drawbacks
* the generated callback script need to be interpreted prior execution, introducing some overhead (and some events could be called a lot of times), and
* although easy, building the script statement as a string fells clumsy.

Other embedding APIs (such as NPAPI, just to name one) offer some kind of function/method calling facility. That way, no interpretation is needed (just a symbol look-up and execution) and the programmer will surely feel smarter in using a well-defined API rather than hacking the callback into the VM.

I guess this can be done both for functions and class methods (static symbols) and instance methods (dynamic symbols). For the latter, I guess the instance variable name (or pointer?) should be passed, but that won't be an issue.

These are some random thoughts I wrote for you to comment. The surely need to be refined, but might be a starting point for a discussion.

**Comment by munificent** [comment]
Yes, thank you for filing this! I've been thinking about this exact issue for the past couple of weeks. It's a high priority for me to fix it. I have some rough ideas, but I haven't had a chance to sit down and work on them.

It's a bit trickier in Wren compared to, say, Lua because we have both modules and most executable code lives in methods in classes. In Lua, you can just say "call the function named 'blah'" and Lua look for a variable in the global scope with that name and invokes it.

In Wren, it's more likely that you'll need to also say which module and class you should look in. (We could use functions stored in variables for this, but I don't think it feels idiomatic.)

Given that calling into Wren like this may also be performance critical, I'd like to avoid having to hash the names every time. So what I'm currently thinking is that I can add an API that says "give me a handle to static method __ in class __ in module __". That will return an opaque data structure. Then you can use that to provide some arguments and invoke it later.

What do you think?

**Comment by bjorn** [comment]
Actually I don't personally like very much the "call some predefined function in the script" approach sometimes taken. In both my hobby projects and at work, we instead just execute the script and the script is expected to register handlers using exposed API functions. The handlers are function references that are then called from the C/C++ side by pushing them on the stack along with their parameters and calling them.

In general I think this should also perform better because it saves the lookup each time you want to call something, and you can also quickly skip calling anything when no handler was registered.

**Comment by MarcoLizza** [comment]
> It's a bit trickier in Wren compared to, say, Lua [...]

Yep, in fact in Lua si dead simple.

> So what I'm currently thinking is that I can add an API that says "give me a handle to static method __ in class __ in module __". That will return an opaque data structure. Then you can use that to provide some arguments and invoke it later.

That's exactly what I had in mind.

Having a handle to the method to call it later is quite handy e performance friendly.

*(and, in fact, it is something that other API offers, too... such as the already mentioned NPAPI if I recall right)*

In my opinion it would be useful also to have a way to call non-static methods, too, although this would be trickier. Perhaps by means of the opaque type referring instance variable we could achieve dynamic dispatch, too.

> Actually I don't personally like very much the "call some predefined function in the script" approach sometimes taken.

True. I'm also really not very fond of this approch, as I always (if possible) provide a "registration" function through which you will be passing the name (if not the reference itself) of the callback to be called. Not hardcoded names, please.

*(with some minor exceptions such as a `main` callback or something like that)*

**Comment by munificent** [comment]
> Actually I don't personally like very much the "call some predefined function in the script" approach sometimes taken. In both my hobby projects and at work, we instead just execute the script and the script is expected to register handlers using exposed API functions. 

Yeah, in practice, for larger applications I think that's a cleaner approach. But I don't want to rule out users who want to do this for simple cases.

There's also the problem that Wren doesn't support the ability to register handlers in this way either. :grimacing: Either way, it's an open problem how to cause a blob of Wren code to run from C without interpreting a string.

**Comment by munificent** [comment]
OK, I've got a first pass at an API for this. In C, it lets you get a handle to a method bound to some object. Then you can call that as much as you want, passing in arguments from C. When you're done, you release the handle. It looks like this:

```c
WrenMethod* method = wrenGetMethod(vm, "main", "Foo", "bar(_,_,_,_,_)");
wrenCall(vm, method, "bdins", true, 12.34, 5678, NULL, "some string");
wrenReleaseMethod(vm, method);
```

It should be pretty efficient, and you can call `wrenCall` repeatedly on the same handle. I *think* the API is pretty nice, but I'd definitely like feedback on it.

**Comment by MarcoLizza** [comment]
Radical! :metal:

I really like your choice in using a variable-argument-list to pass the actual parameters to the mathod call (the other option being an open array of some customary "variant" type). Sleek.

Also, having to pass the "compacted" actual types (fells like using `getopt` :wink:) on each call, may sound a bit too much of book-keeping but I find it versatile. It enables the very same `WrenMethod` variable to be called different times with different values/types (if needed and/or make sense).

Unfortunately, I can't conduct some experiments until tomorrow. I'm looking forward in giving a try and write some example use-cases!

*(in fact I'm needing this feature in the engine I'm developing)*

By the way, I also have in plan to do a regression test to check whether the MSVC build is still "warning-free" following the generous recent changes/additions.

**Comment by munificent** [comment]
> I really like your choice in using a variable-argument-list to pass the actual parameters to the mathod call (the other option being an open array of some customary "variant" type). Sleek.

Yeah, I think doing a variant in C-land would add a lot of complexity and overhead for wrapping.

> It enables the very same WrenMethod variable to be called different times with different values/types (if needed and/or make sense).

Yup, that's what I had in mind. :) It does feel a bit redundant to pass the signature into `wrenGetMethod()` and then pass the argument type string to `wrenCall()`. I'm considering trying to unify those, so you'd do:

```c
WrenMethod* method = wrenGetMethod(vm, "module", "variable", "someMethod(s,b,i)");
wrenCall(method, "str", true, 123);
```

And that would give you a method handle both to some typed argument list. If you wanted to call the same method with different argument types, you could just get multiple handles to the same method with different arg types.

But, now that I think about it, this will add a decent amount of complexity to the implementation, so it's probably not worth doing. There is something nice about having the "format string" right next to the argument list. Makes it easier to keep them in sync.

> (in fact I'm needing this feature in the engine I'm developing)

I have a little not-even-a-toy game engine that also needed this. :)

> By the way, I also have in plan to do a regression test to check whether the MSVC build is still "warning-free" following the generous recent changes/additions.

Sounds good, thanks! Travis is at least doing the C++ build now, so that should flush out some of these errors.

**Comment by bjorn** [comment]
I can recommend (AppVeyor)[http://www.appveyor.com/] for automatic MSVC builds. Been using it for my application for a while now (though with MinGW) and it can also push binaries / installers somewhere (like directly to github release tags).

**Comment by MarcoLizza** [comment]
> Yeah, I think doing a variant in C-land would add a lot of complexity and overhead for wrapping.

Agree. Moreover, the additional housekeeping code needed to initialize the array and/or the contained variants would clutter the code very soon. Var-args have been often overlooked, it's nice to see them used in a practical and effective way. :+1: 

> It does feel a bit redundant to pass the signature into wrenGetMethod() and then pass the argument type string to wrenCall()

Yes, it is. In fact that was my first thought. But it would be for some reason. In fact...

> But, now that I think about it, this will add a decent amount of complexity to the implementation, so it's probably not worth doing.

... that's what I ended up considering. Registering the signature in `wrenGetMethod()` would mean keeping track of it inside the method opaque type. This won't be overkill, since the simplest way to do this is to store the string itself... but is it worth? There's not a lot of pre-processing you could do when registering the signature itself, a part storing the signature specification string.

As a general practice, I tend to prefer not to allocate/duplicate strings when not needed (or avoidable).

> There is something nice about having the "format string" right next to the argument list. Makes it easier to keep them in sync.

True. This is some kind of auto-documenting feature I kinda like. 

> I have a little not-even-a-toy game engine that also needed this. :)

Nice! :+1: 

> Sounds good, thanks! Travis is at least doing the C++ build now, so that should flush out some of these errors.

Fine, I'll let you know tomorrow!

> I can recommend AppVeyor for automatic MSVC builds.

Thanks, @bjorn! I'll git it a try.

*(altough having a full MSVC CI is beyond the scope of what we are doing here with Wren)*
