### ISSUE TITLE
Passing basic types by reference

### ISSUE THREAD

**Issue by Nelarius** [munificent/wren#206]
Is passing a basic type, e.g. `Bool`, `Num`, by reference currently possible in wren? 

The following dummy program doesn't quite have the intended results, as the variable `x` at file scope is unaffected after being passed to the function `decrementer`:

   
    var decrementer = new Fn { |val|
    	val = val - 1
    }
    var x = 10
    IO.print( x )   // x is 10
    decrementer.call(x)
    IO.print( x )   // x is still 10

Is something like `x.ref` returning a reference to the underlying object being planned/not planned?

**Comment by MarcoLizza** [comment]
I'm very fond of the pass-by-reference idiom in C++, but in my opinion this is something beyond Wren scope.

In Wren's perspective it's advisable, in my opinion, to rely only on return values. That is, in your example, the `decrementer` returns the decremented value. This also solves the corner case you encounter when passing an immediate number value.

**Comment by munificent** [comment]
> Is passing a basic type, e.g. Bool, Num, by reference currently possible in wren?

Whether or not it is is actually undetectable since those objects are immutable.

```
var decrementer = new Fn { |val|
    val = val - 1
}
```

Here, you aren't modifying a number object, you're just creating a new number and assigning it to the local variable `val`. Likewise, when you call it, you aren't passing the *variable* `x`, you're passing the value stored in that variable.

Collections are passed by reference, of course:

```
var f = new Fn { |val|
    val.add(1)
}

var x = []
f.call(x)
IO.print(x)   // [1]
```

But, again, *assigning* to a variable is different:

```
var f = new Fn { |val|
    val = [1]
}

var x = []
f.call(x)
IO.print(x)   // []
```

I don't have any plans to add explicit pass-by-reference to Wren. Many languages don't have it—Java, Ruby, Python, JS. It's useful in C++ because it has value semantics but isn't as needed in a GC language like Wren. (Not that it isn't useful—C# has it.)

If you're using pass-by-reference for output parameters, like @MarcoLizza says, in most cases you can just return stuff. You can always return a list of multiple results.

**Comment by Nelarius** [comment]
Yeah, I guess I'm just trying to use wren like it's C++ a little bit too much at the moment. Gonna sit in a corner and rethink how I write wren code now!
