### ISSUE TITLE
Odd newline and parenthesization rules

### ISSUE THREAD

**Issue by zeckalpha** [munificent/wren#24]
This works:

~~~ Dart
class Set {
  // ...

  - that {
    // Set minus
    return new Set(
      _list.where(
        fn (element) {
          return (
              !that.contains(element))
        }))
  }
}
~~~

But when I reformat to make the parens at the end look "better", this fails:

~~~ Dart
class Set {
  // ...

  - that {
    // Set minus
    return new Set(
      _list.where(
        fn (element) {
          return (
              !that.contains(element)
          )
        }
      )
    )
  }
}
~~~

Okay, that isn't that much better, but I don't think it should fail.

Error message:

~~~
[example/set.wren line 10] Error on newline: Expect ')' after expression.
[example/set.wren line 11] Error on ')': Expect '}' after block body.
[example/set.wren line 11] Error on newline: Expect ')' after arguments.
[example/set.wren line 12] Error on '}': Expect ')' after arguments.
[example/set.wren line 13] Error on ')': Unexpected token for expression.
[example/set.wren line 14] Error on ')': Unexpected token for expression.
~~~

**Comment by zeckalpha** [comment]
Not sure what's changed here, but this problem still remains with newer syntax. This works:

~~~
class Set {
  // ...
  -(that) {
    // Set minus
    return new Set(
      _list.where { |element|
          !that.contains(element)
      })
  }
}
~~~

This fails:

~~~
class Set {
  // ...
  -(that) {
    // Set minus
    return new Set(
      _list.where { |element|
          !that.contains(element)
      }
    )
  }
}
~~~

Error message:
`[example/set.wren line 8] Error on newline: Expect ')' after arguments.`

**Comment by munificent** [comment]
Ah, yes. So the issue is that after it parses:

```
      _list.where { |element|
          !that.contains(element)
      }
```

It's looking for either a `,` to indicate the next argument, or `)` to indicate the end of the argument list. Instead, it sees a newline.

My personal preference is to put the `)` right after the `}`, which sidesteps this issue. But I think it may be more usable for others to ignore a newline here.

I'm trying to think if that will cause any unintended side-effects. I don't *think* so, but it probably does imply we'd also want to ignore newlines before `)` in a parenthesized expression, and `]` in a list literal, etc.

That makes me wonder if we should change the overall rules for ignoring newlines. I think they've sort of grown hairier over time. One idea I had was that the parser could keep track of if it's in statement or expression context, and discard all newlines when in the latter.
