### ISSUE TITLE
If superclass clause evaluates to null, is implicitly treated as Object

### ISSUE THREAD

**Issue by gsmaverick** [munificent/wren#246]
It seems that super classing behaviour is different if the super class was implicitly defined as seen in the following example:

```scala
class B is A {}

class A {
  new (value) { IO.print("A ", value) }
}

class C {
  new (value) { IO.print("C ", value) }
}

class D is C {}

var d = new D("test")
var b = new B("test")
```

If you run this script you get the following error:
```
wren gavin$ ./wren superclasses.wren 
C test
B does not implement 'new(_)'.
[main line 14] in (script)
```

It should print out `B test` as well.

**Comment by bjorn** [comment]
Shouldn't this be expected to fail on the `class B is A {}` line, given that A has not been defined at that point?

**Comment by MarcoLizza** [comment]
> Shouldn't this be expected to fail on the class B is A {} line, given that A has not been defined at that point?

That's a good point, being the common programmer used in pre-declare everything before it's use.

What @gsmaverick spotted is that it seems that `B` is bound to an implicit (alas unknown) "empty" class `A`.

I'm not sure, but given the dynamic nature of Wren, I think it could safely proceed in binding class `B` to class `A` even if the latter is not defined yet.

**Comment by bjorn** [comment]
> I'm not sure, but given the dynamic nature of Wren, I think it could safely proceed in binding class B to class A even if the latter is not defined yet.

No, this won't work because of two things:

* **Fixed object layout:** As far as I know Wren determines the size of an instance when its class is defined, which necessarily includes the space needed for storing any members of superclasses. This means you can't define a superclass afterwards.

* **Copy-down inheritance:** Methods are copied down from the superclass, to speed up the lookup when they are called. Again, this means the superclass needs to be defined first.

* **A single-pass compiler:** The above issues may have been resolvable by doing two passes through the source code. Yet, Wren only does a single pass to generate the bytecode.

You can read about these things at http://munificent.github.io/wren/performance.html. Of course, I may be wrong with my conclusions since I do not know the implementation. Maybe there is a reason for accepting `class B is A {}` when A is undefined that I'm not aware about.

**Comment by MarcoLizza** [comment]
> You can read about these things at http://munificent.github.io/wren/performance.html.

Yep, did know this. Mine was just a speculation on the way Wren *could* work, not the way works right now. :wink:

It is due to *copy-down inheritance* that I wrote that *perhaps* Wren is interpreting `A` as an implicit empty class. This is coherent with the behaviour @gsmaverick depicted, i.e. that `new(_)` is not implemented (since the `A` was empty then `B` is defined).

**Comment by munificent** [comment]
Oh, ha. This is just a straight up bug. :grin:

Wren has a single bytecode instruction for creating a class, `CODE_CLASS`. It uses that both for class definitions with an explicit superclass (`class Foo is Bar { ... }`) and those without (`class Foo { ... }`). For the former, the compiler compiles the superclass class (here `Bar`) and puts that on top of the stack. The `CODE_CLASS` uses that to find and bind the superclass. For the latter, the compiler just pushes `null` and the VM code for `CODE_CLASS` treats `null` as "inherit from Object".

So in this code:

```dart
class B is A {}
```

A evaluates to `null` since it hasn't been defined yet. Then `CODE_CLASS` thinks that's a class definition without a superclass at all, so you get `B` inheriting from `Object`. There's no `new(_)` in object, so you get a method not found error.

You'd get the same bug if you did:

```dart
class B is null {}
```

Using a `null` sentinel value to mean "no superclass" was just a dumb idea on my part because a superclass class can also (erroneously) evaluate to `null`. Instead, we should probably put an operand in the bytecode itself after `CODE_CLASS` to determine if a superclass should be looked for or not.

Then, a superclass clause that evaluates to `null` should be a runtime error just like any other non-`Class` superclass. Good job spotting this!

**Comment by munificent** [comment]
> As far as I know Wren determines the size of an instance when its class is defined, which necessarily includes the space needed for storing any members of superclasses.

Yes... mostly. The challenge is that a class's superclass isn't known at compile time. When you have `class Foo is Bar`, the compiler doesn't know what value `Bar` is going to evaluate to until the code is executed. You can write code like:

```dart
class Base {}
class TuesdayBase {}

class Derived is (todayIsTuesday ? TuesdayBase : Base) {}
```

(Not that I'd call this good code!) But even a simple variable name for the superclass can't be resolved until runtime.

At the same time, we do need to know how big an instance of a class is and what offsets all of its fields are at. To handle that, there's a very simple "bind" step when a subclass is defined at runtime. During that, it [adjusts the total number of fields to take into account its superclass's fields](https://github.com/munificent/wren/blob/master/src/vm/wren_value.c#L63).

Also, whenever a method is bound to a class (or subclass) Wren [runs through its bytecode and shifts all of its field accesses down](https://github.com/munificent/wren/blob/master/src/vm/wren_compiler.c#L3204) to compensate for the superclass's fields now that we know how many there are.

So, it's *mostly* a single-pass compiler. There's just one other very fast patch-up for method bodies when they get bound. This burns some CPU cycles at class definition time, but makes field access faster at runtime. Always a good trade-off.

**Comment by gsmaverick** [comment]
What an informative bug :) Lots of interesting details were learned! I'm going to tackle a fix for this issue and see where I end up.

**Comment by bjorn** [comment]
```dart
class Derived is (todayIsTuesday ? TuesdayBase : Base) {}
```
Woah, I had totally not expected that to be possible! I'm sure it has its advantages somewhere. Thanks for all the details!

Just playing around here:
```dart
var defineFoo = new Fn {|superclass|
    class Foo is superclass {
        new {
            super
            IO.print("Foo created")
        }
    }
    return Foo
}

class Bar {
    new { IO.print("Bar created") }
}

var Foo = defineFoo.call(Bar)
IO.print(new Foo)
```
Wren is much more dynamic than I thought. :-)
