### ISSUE TITLE
"list" -> "toList"

### ISSUE THREAD

**Issue by munificent** [munificent/wren#248]
Now that Sequence has a `list` method with no "to" to convert a sequence to a list, it makes me wonder if we should rename `toString` to just `string`. For example:

```dart
var digits = 123.string
[1, 2, 3].string
someObject.string
```

Thoughts?

**Comment by MarcoLizza** [comment]
I already put some thoughts about it, in the past.

I'm not a big fan of the Java-fashioned "toString" method itself, being misused quite a lot.

However, the "to" prefix has the major benefit in carrying the precise semantic of the attribute/method itself. That is, computing the string representation of an object. 

Naming it just "string" may be a bit puzzling, since one could ask "what string it's returning?".

An alternative is the prefix "as", which I find even more clear and precise. 

But, perhaps, the "to" prefix is a common idiom one has no real use in changing right now.

**Comment by ianmackenzie** [comment]
I agree - I think I prefer `toString`/`toList` or `asString`/`asList` to just `string`/`list`, because they lead to expressions that read more naturally as descriptive phrases. The `toString` name is pretty well entrenched in other languages and I think it arguably makes it more clear that a conversion is happening (to me 'as' implies something more like an up or down cast), but I'd be happy with either

**Comment by bjorn** [comment]
Well, my initial reaction to it is, it doesn't feel nice to read it. To "string something" does not work as a verb, as opposed to "list a sequence". But maybe it just takes getting used to.

I think `asString` sounds too much like a cast, btw.

**Comment by ianmackenzie** [comment]
I also think there's a nice symmetry with 'to' and 'from': `var str = num.toString`, `var num = Num.fromString(str)`.

**Comment by MarcoLizza** [comment]
@ianmackanzie, I agree with the symmetry being a nice plus.

**Comment by MarcoLizza** [comment]
@bjorn, I appreciate that. :)

However, I do think the the naming itself should always be consistent with the general semantic that the method itself conveys. By no means I think that every accessor need to be prefixed with "to". :wink:

*ps: and, by the way, I also do think that "asXXX" sound a bit like a cohercion...*

**Comment by munificent** [comment]
OK, I'm convinced that `to` is better. I'll leave this bug open to fix `list` instead of `toString`.

Regarding `as` versus `to`, the designers of the Dart core libraries have what is I think a smart rule. A `to` method means "create a new object whose contents are based on the receiver" where `as` means "create an object that still refers to the original receiver".

In other words, if you change the original object, you will see the change in the result of an `as` method, but not `to` method. An `as` method is a *live view* of the object as a different type. A `to` method is a *snapshot conversion* of a new object.

(In cases where the original object is immutable, this difference isn't visible. In that case, I think Dart defaults to `to`.)
