### ISSUE TITLE
Cannot create new instance from method if class name is lowercase

### ISSUE THREAD

**Issue by krypt-n** [munificent/wren#251]
Hi, the following is a simplified example of unexpected behaviour I encountered

    class foo {
        test {
            var barz = new foo
            return barz
        }
    }
    var bar = new foo
    bar.test

wren cli output:

    foo does not implement 'foo'.
    [test.wr line 3] in test
    [test.wr line 8] in (script)

with `'foo'` refering to the constructor call in `test`.

Defining a constructor of any arity doesnt help.
Is this a bug/undocumented feature or is there a mistake in my example?

/e updated examples:

    class foo {
        test {
            new foo
        }
    }
    (new foo).test

fails in test

    class Foo {
        test {
            new Foo
        }
    }
    (new Foo).test

runs without error messages

**Comment by krypt-n** [comment]
Ehm...it does work if the class name starts with an uppercase F

**Comment by gsmaverick** [comment]
This is intended behaviour as any lowercase name inside of a class method is only looked up as a method on the class.

**Comment by krypt-n** [comment]
Well, that makes lowercase typenames virtually unusable. Why are they allowed?

**Comment by lluchs** [comment]
You can have local classes returned by getters:

```dart
class Foo {            
  bar {
    class local {
      new {
        IO.print("bar")
      } 
    } 
    return local
  } 
  
  new {
    var b = new bar
    IO.print("Foo")
  } 
}

new Foo
// bar
// Foo
```

**Comment by MarcoLizza** [comment]
Nobody defines classes and UDT with lowercase or camelcase convention. :) 

Aside from jokes, I think that language and grammar based styles are a good thing...

**Comment by munificent** [comment]
Oh, that's interesting.

This is a natural consequence of the naming and scoping rules, but not something I'd considered when I changed how names are looked up. Like @gsmaverick says, it's because lowercase names are handled differently than capitalized ones, especially inside methods.

If a lowercase name isn't defined as a local variable inside the method, it's interpreted as method call with an implicit `this.`.

In this case, the behavior may not be ideal, but I think it's tolerable to keep things simple, I suppose.
