### ISSUE TITLE
Deeply nested objects can result in a stack overflow in the garbage collector

### ISSUE THREAD

**Issue by rxi** [munificent/wren#280]
Due to the garbage collector using recursion on the C stack to mark the objects, deeply nested objects can result in a stack overflow. On my system, the following example results in one:

```
var head

for (i in 1..400000) {
  head = { "next" : head }
}

IO.print("done")
```

gdb backtrace:

```
Program received signal SIGSEGV, Segmentation fault.
0x000000000040a92c in wrenMarkObj ()
(gdb) bt
#0  0x000000000040a92c in wrenMarkObj ()
#1  0x000000000040ab78 in wrenMarkObj ()
#2  0x000000000040ab85 in wrenMarkObj ()
#3  0x000000000040ab85 in wrenMarkObj ()
...
```

Moving to a tri-color garbage collector would fix this issue; additionally it would also act as the first step towards the garbage collector being able to work incrementally.

**Comment by munificent** [comment]
Ah, yes. This is a known issue, but it's good to have a tracking bug.

At some point, I do want to move to incremental. The throughput will likely go down, but it will have better latency, which is the right thing for games where I hope Wren will be useful.

I don't have any near term plans to do this, though. It's one of those kinds of big changes where I want to have a good volume of real-world empirical performance data before I work on it. Otherwise, there's a risk of optimizing for unrepresentative benchmarks and not making things actually better for real users.

**Comment by iwillspeak** [comment]
I'd like to take a look at moving the current mark and sweep implementation to be iterative to fix this in the short term if that's ok? I'm thinking of some simple two phase tri-colour approach to get rid of the need for a recursive mark phase.

**Comment by munificent** [comment]
My only hesitation would be if it adds a lot of complexity. But if the implementation is fairly straightforward, that sounds great. I'd definitely be happy to get rid of the recursive marking.

**Comment by iwillspeak** [comment]
I'll see how it turns out. What I have in mind shouldn't be too different
from the current implementation. I'll open a pull request when I've got
something to show and we can discuss it more there.

Bob Nystrom wrote:

**Comment by munificent** [comment]
This is fixed now. Thanks, @iwillspeak!
