### ISSUE TITLE
Wren for microcontrollers?

### ISSUE THREAD

**Issue by anfred** [munificent/wren#282]
Is wren small enough to put on 1mb of flash?  64Kb of ram?   If so, I think it would be great for making robots!

**Comment by minirop** [comment]
probably, on my windows 7, the REPL binary is 1.6Kb

**Comment by lluchs** [comment]
Wren's only numeric type are floating-point numbers. Most microcontrollers don't support those, so you'll probably have to rely on emulation by the compiler. Performance definitely won't be great.

**Comment by RickGlimmer** [comment]
Microcontrollers would benefit greatly if there are datatypes for bit, nibble, byte, etc.
Not sure if that is doable, but i would be greatly interested.

**Comment by anfred** [comment]
It seems that the stm32 cortex M4 processor supports floating points.  This would mean the stm32F411RE would likely be the lowest cost board, at $11.  I have one of those boards, but I am not even close to capable of writing firmware for it!  It is nice to know wren could be compatible with some low cost microcontrollers though.  I am still curious about the ram constraints; e-lua does ok with 20kb of ram, but it really needs 64kb to do well.  Thanks for the replies!

**Comment by munificent** [comment]
Yes, it should go pretty small. The implementation is tiny, as is the core library. It's pretty parsimonious with memory allocation and you can control the heap size.

Two things that might be tricky are:

1. Using only `double` for its numeric type. If there's really a lot of interest in supporting devices that don't support floating point, it would be possible to set a `#define` that lets you control Wren's numeric type.

2. Using C99/C++89. If you can't get a relatively modern (as in the past two decades!) compiler for the chip, you may have trouble compiling Wren.

I'm going to close this bug out since there's no real work to do here, but I would love to see people try running Wren on small devices and let us know how it goes. If you run into concrete issues, I'd be happy to work on fixing them.
