### ISSUE TITLE
Curly brace on a new line

### ISSUE THREAD

**Issue by BrothaOnAcid** [munificent/wren#307]
Seems like I finally found an alternative to **dirty LUA** !
Toying with embedding right now. I really like da language !
But I'm struggling with one nasty thing - curly brace on a new line causes a compiler error ! =(
And I've been CURLY-BRACE-ON-A-NEW-LINE type of guy for a long time ! It certainly looks more **clean** or **symmetric** to me.

So this WREN code works perfectly:
```
var my_little_func = Fn.new { | arg0, arg1 |  
    System.print( "hey" )
}

var my_little_func2 = Fn.new {
    System.print( "hey" )
}

class DaClass {
    construct new() {
        System.print( "yo" )
    }
}
```

And I'd like to write it this way:

```
var my_little_func = Fn.new
{ | arg0, arg1 |   
    System.print( "hey" )
}

var my_little_func2 = Fn.new
{
    System.print( "hey" )
}

class DaClass
{
    construct new()
    {
        System.print( "yo" )
    }
}
```

So is it **that important** and couldn't be changed ?
Seems like I'm going to write some kind of source preprocessor ? ;]

**Comment by minirop** [comment]
the language uses newline as separator and allowing that would make the grammar ambiguous.
```
var my_little_func2 = Fn.new
{
    System.print( "hey" )
}
```
this code is correct and is a function call and a block containing only one statement. To allow that, we would have to change the separator (semicolon like in C?) or disable *anonymous* blocks.

**Comment by ppearson** [comment]
Same with me - I'm very interested in looking at using Wren (been playing with it for a week now and generally like what I see) over Lua and possibly Python as an embedded language for a couple of projects, but hanging braces really puts me off.

I know this is generally personal style thing, but I used to work in the defence industry (where code safety was critical), and there's a reason the vast majority of coding standards there enforced matching indents in C and C++ (and tab widths of over two spaces): it makes logic more obvious *at a glance* as opposed to having to spend brain power for half a second every time you look at a new section of code to match the braces.

So while I understand it *might* be a style choice taken (and it's certainly within your right to make that decision), if it is, why doesn't the C code using hanging braces? :)

**Comment by davidzchen** [comment]
As @minirop explained, this particular issue was not a _style decision_ but rather a result of the design of Wren's grammar, where newlines are used as separators. Allowing braces on the next line in some cases would cause ambiguity unless changes are made to Wren's grammar. As he mentions, one of the reasons why C allows hanging braces is that C uses semicolons as separators while Wren uses newlines, and one of the ways that Wren could possibly support both brace styles is by switching to semicolons for separators.

@ppearson - We can take this discussion offline, but I am curious about other aspects of the style guides you used while working in the defense industry because coding style is something that I have a particular interest in. :) Are there any publicly published coding conventions that are similar to the ones you used?

**Comment by ppearson** [comment]
@davidzchen: JSF's is the best known: http://www.stroustrup.com/JSF-AV-rules.pdf.

Basically the premise (and ADA was designed with this in mind as well) is that it's better to be a bit more verbose (in terms of lines of code, variable names, etc) if code's more obvious to the eye as well as enforcing things that prevent ambiguities which can cause trouble (dangling else if braces aren't used around every control statement).

**Comment by IsaacWoods** [comment]
Perhaps we could use a different piece of syntax for anonymous blocks (although in my option, they are not too much of a sacrifice), but Wren would become a lot more new-user friendly if we could allow this choice. Huge numbers of programmers and industry coding-styles place braces on new lines, so allowing this would be great.

**Comment by davidzchen** [comment]
@ppearson Thanks! Interesting, the JSF convention uses a 120-character line length limit. Personally, I find 80 character lines, 2 space indents, and hanging braces the most readable, which is also the convention used by the [Google C++ Style Guide](https://google-styleguide.googlecode.com/svn/trunk/cppguide.html), though I can see how keeping the brace on its own line might be more readable in some cases if your style guide uses longer line lengths.

My impression is that this particular property of Wren is mainly a result of using newlines as a separator rather than semi-colons. [Go](https://golang.org/) actually has the exact same property and also uses newlines as separators. Based on my knowledge of language grammars, allowing braces on a new line might be non-trivial unless a different character is used as the separator.

My view is that it is most important to be consistent and would prefer to use Go's opinionated approach to  use an automatic formatting tool such as [`gofmt`](https://golang.org/cmd/gofmt/) to resolve the style issue.

In any case, I'll to leave it to @munificent and the Wren developers to determine how difficult of a change this would be and make the final decision on whether Wren should support this.

**Comment by ppearson** [comment]
@davidzchen: I personally don't see what long code lines have to do with it - I've had to work on code bases using hanging braces and 2 space indents in the past, and a lot of the time, people added a blank new line after the hanging brace to clearly demark where the code started and the list of function parameters ends (which is one thing hanging braces makes really subtle IMO), and they often did the same with control statements, so might as well have put a brace on that line.

Anyway, this isn't really a place for a debate on this, and everyone has their own opinion that they think is right, so I'll drop it now, but on the subject of automatic pre/post formatting, that's another thing - along with opinionated languages (Go, Rust) - that just makes me think "what's the point, I'll use something else." Might be petty and non-logical, but I personally think my choice of coding style **is** logical.

A lot of people also bring in the "The IDE can highlight braces for you" argument, which while true in a sense falls down once you start diffing code or using a code review tool, so IMO it's a pretty weak one.

**Comment by davidzchen** [comment]
@ppearson I prefer having multiple files open side by side. As a result, my experience is that with long lines, it takes more time to find the opening brace if it is at the end of the line because I end up needing to scroll to the right to see the end of the line. Having the brace on its own line would prevent me from having to scroll horizontally to match braces.

This is why I prefer the 80 character line length, even though many would consider this old-fashioned, simply because it allows me to have multiple files open side by side and be able to see all the code without having to scroll horizontally.

To close the debate on style: we are all passionate about the style that we prefer. It is a property of a good engineer. There are equal numbers of engineers and organizations who prefer hanging braces as those who prefer braces on its own line, and I am sure there are equal amounts of reasoning (both logical and emotional) for both styles. _Different people simply find different styles more readable._

Looping back to how Wren can be improved: currently, this limitation is a property of the language, and allowing braces on the next line may require non-trivial, backwards-incompatible changes to the language's grammar. It is up to @munificent et al. to decide the philosophy of the language and whether such a change should be made.

In any case, I am sure that the current design is a result of the decision to get rid of semicolons rather than a preference for hanging braces. After all, _Wren's codebase itself_ does not use hanging braces but puts braces on its own lines. :)

**Comment by munificent** [comment]
> In any case, I am sure that the current design is a result of the decision to get rid of semicolons rather than a preference for hanging braces.

It comes from two things:

1. A desire to get rid of semicolons.
2. A desire for Wren code to be *consistently* formatted regarding braces.

As you noticed from looking at the C code, I personally prefer opening braces on the next line. But what I *really* care about is consistency. When I code in Dart or Java, I use hanging `{` because that's the prevailing style there.

Using hanging `{` in Wren is a really simple way to accomplish both of those goals. It makes the language easier to parse with significant newlines and it encourages code to be more consistent.

I also find I like how it looks in Wren. Compared to C, statements in Wren tend to be shorter and visually lighter-weight. In C, the extra mostly-blank `{` line helps open things up some, but I don't feel Wren code needs that as much.

But, really, it's "easy to parse" + "enforced consistent style". :)

Thank you for bringing this up, though! It's nice to have a record of the discussion.
