### ISSUE TITLE
Hierarchical naming?

### ISSUE THREAD

**Issue by hauptmech** [munificent/wren#316]
I tried to do `var P = System.print` as a typing aid and discovered that System is a class, not a module. A dig through the code shows that no state is being carried by System though.

Is this because classes are the only way group names?

**Comment by munificent** [comment]
> Is this because classes are the only way group names?

It's more that they're the natural grouping for *methods*. You can have functions in Wren, and you can stuff them in variables at any level of scope, but those aren't quite the same thing as methods. (This is unlike, say, JavaScript and Pythons, where methods are pretty much just functions hanging off objects.)

Wren is closer to Smalltalk in that named methods are very core to the language. Where `foo.bar()` in other languages means roughly "look up bar", then "invoke that function", in Wren it's a single atomic "invoke the bar() method".

This is significant because it ties into Wren's concept of [signature](https://munificent.github.io/wren/method-calls.html#signature). You can't grab a handle to a method without invoking it, because it's not clear which of the many possible overloads you might have in mind.

I do agree `System.print()` is kind of verbose.

I'm toying around with some ideas for better support for either top-level functions or top-level methods to try to help for cases like that, though I'm not sure how well they'll work out. See the last couple of messages on the mailing list for some more details.

There is another prosaic reason around `System.print()` versus a bare function name. Scoping is based on capitalization in Wren (as in Ruby). Inside a method in some class, `print()` would be interpreted as `this.print()` which isn't what you want here. To avoid that, you'd have to call it `Print()`, and that seems strange looking to me for a function name. (Though it is pretty much what Go does.)

**Comment by hauptmech** [comment]
I'm starting to understand. It might be clearer in the documentation to say that Wren has no functions (or no top level functions), only classes and methods on those classes (or messages to those classes). The Fn class is a class, not a function after all.

    var P = Fn.new {|str| System.print(str) }

 will be fine once () -> .call() is integrated.

Regarding how to specify a signature if you end up wanting it; what you use internally is nice and clean. 

    var X = unambiguous_function(_,_)

Thanks for taking the time to illustrate what you did here.

**Comment by munificent** [comment]
> I'm starting to understand. It might be clearer in the documentation to say that Wren has no functions (or no top level functions)

It does have functions. You can even create one and store it in a top level variable. The differences, compared to some other languages are that:

1. Functions are different from methods. They have different syntax, slightly different ways of being invoked, different approaches to handling arity, etc.
2. There is no syntax for a named function declaration.
3. There isn't currently a dedicated literal form. Instead, they are implicitly created through block arguments, like Ruby.

But, semantically, Wren does have functions and they do all of the nice things you want: they're first class, close over their lexical scope, etc.
