### ISSUE TITLE
Odd behavior/segfault.

### ISSUE THREAD

**Issue by boardwalk** [munificent/wren#351]
I'm not 100% I'm using the API correctly, but here's some code:

```c
#include <stdio.h>
#include <wren.h>

static void writeFn(WrenVM* vm, const char* text) {
  fputs(text, stdout);
}

int main() {
  WrenConfiguration config;
  wrenInitConfiguration(&config);
  config.writeFn = writeFn;

  WrenVM* vm = wrenNewVM(&config);

  const char* code =
"class Test {\n"
"    static [key] {\n"
"        System.print(\"get\")\n"
"        System.print(this)\n"
"        System.print(key)\n"
"        System.print(\"get done\")\n"
"        return __data[key]\n"
"    }\n"
"\n"
"    static [key]=(value) {\n"
"        System.print(\"set\")\n"
"        System.print(this)\n"
"        System.print(key)\n"
"        System.print(value)\n"
"        System.print(\"set done\")\n"
"        return __data[key] = value\n"
"    }\n"
"}\n";

  wrenInterpret(vm, code);

  wrenEnsureSlots(vm, 1);
  wrenGetVariable(vm, "main", "Test", 0);
  WrenValue* cls = wrenGetSlotValue(vm, 0);
  WrenValue* setCall = wrenMakeCallHandle(vm, "[_]=(_)");
  WrenValue* getCall = wrenMakeCallHandle(vm, "[_]");

  wrenEnsureSlots(vm, 3);
  wrenSetSlotValue(vm, 0, cls);
  wrenSetSlotString(vm, 1, "key");
  wrenSetSlotString(vm, 2, "value");
  wrenCall(vm, setCall);

  wrenEnsureSlots(vm, 2);
  wrenSetSlotValue(vm, 0, cls);
  wrenSetSlotString(vm, 1, "key");
  wrenCall(vm, getCall);

  return 0;
}
```

Compiling and running:

```text
% gcc -o test test.c -g -lwren -lm && gdb -ex run -args ./test
...
Starting program: /home/boardwalk/test
set
Test
key
System
set done

Program received signal SIGSEGV, Segmentation fault.
0x000000000040335c in wrenEnsureSlots ()
```

So first thing is that while `this` and `key` get printed properly, I get `System` where I'd expect `value`, like the call to System.print is "bleeding into" the current frame.

Then I get a segfault in my 3rd call to ensure slots. Interestingly, I don't get one if I remove `return __data[key] = value`. Without the crash get the "bleeding" on the second call too. If I initialize `__data` the crash goes away. So I suppose the first question here is, is a vm supposed to be unusable after a runtime error?

**Comment by munificent** [comment]
One minor bug is that you never initialize `__data` to anything, so you're calling `[_]=(_)` on `null`, and it doesn't support that. Wren doesn't make this easy on you because, by default, it doesn't have any way to report errors to you unless you configure an `errorFn`. If you set that on the config to something like:

```c
static void reportError(WrenErrorType type,
                        const char* module, int line, const char* message)
{
  switch (type)
  {
    case WREN_ERROR_COMPILE:
      fprintf(stderr, "[%s line %d] %s\n", module, line, message);
      break;
      
    case WREN_ERROR_RUNTIME:
      fprintf(stderr, "%s\n", message);
      break;
      
    case WREN_ERROR_STACK_TRACE:
      fprintf(stderr, "[%s line %d] in %s\n", module, line, message);
      break;
  }
}
```

Then it should print the runtime error so you can see the problem. But that doesn't explain why `System` is ending up getting printed.

... Oh, drat. I just realized what's going on. `wrenMakeCallHandle()` is [incorrectly counting the number of parameters](https://github.com/munificent/wren/blob/master/src/vm/wren_vm.c#L1207) in `[_]=(_)`. It stops on `(` and misses the first `_`.

I'll try to fix that soon. Sorry!

**Comment by munificent** [comment]
Oh, and to answer your last question:

> So I suppose the first question here is, is a vm supposed to be unusable after a runtime error?

No. The fiber system is designed to let you safely continue after a runtime error occurs. A runtime error takes down that fiber (and any fibers that called that one), but the VM itself and any other unrelated fibers should be totally fine.

It's crashing here because it's totally confused about how many parameters that method takes.

**Comment by boardwalk** [comment]
Thanks @munificent!
