### ISSUE TITLE
Object references

### ISSUE THREAD

**Issue by zilluss** [munificent/wren#359]
The Lua API has functions to create references to objects (http://www.lua.org/manual/2.4/node19.html). The references can be locked so they won't be GC'ed until they are released. This allows native code to manage object references, read and set properties of objects or call methods on them. This issue is related to #194, but possibly more general.

**Comment by Banane9** [comment]
What about a combination of `wrenGetVariable` and `wrenGetSlotValue`, `wrenSetSlotValue` and `wrenReleaseValue`?

**Comment by zilluss** [comment]
You're probably right. I assumed getSlotValue gives you a slot reference and not an actual object handle, so there really only is the GC part to take care of.

Another important function I forgot to mention is lua_getfield, that is often used in conjunction with the getreference functions. getfield allows you to get the field of an object on the stack by its name. The field value is then put onto the stack where it can be retrieved or called. This is possibly a new issue altogether.

**Comment by Banane9** [comment]
> getfield allows you to get the field of an object on the stack by its name

That'd collide with wren's principle of not letting others access an instance's fields at all, I think.

Let me just test if you could use the call handle functionality for getting properties.

**Comment by Banane9** [comment]
Ok, it works: You can use `wrenGetVariable` to get an instance of a class and put it into a slot and then use `wrenMakeCallHandle` and `wrenCall` on a property getter of it and `wrenGetSlotX` to get the value or `wrenGetSlotValue` to get a reference to it.

**Comment by zilluss** [comment]
Getters work because they are actually functions. I don't know if it breaks any principles, but reading and traversing objects from the host side would be useful.

**Comment by Banane9** [comment]
You can do that with foreign objects at least...

**Comment by paulsapps** [comment]
I thought foreign objects would not get GC'ed?

**Comment by Banane9** [comment]
I meant traversing all their data (as it's under your control anyways)

**Comment by munificent** [comment]
> apart from the referenced value being able to be garbage collected.

The object referenced by a WrenValue won't be GCed until you release the WrenValue. WrenValues are persistent handles to an object so that you can ensure they're stay around as long as you need.

> That'd collide with wren's principle of not letting others access an instance's fields at all, I think.

Partially that. It's also that Wren doesn't *know* the names of an object's fields after its been compiled. Field names are compiled to offsets into the instance's field array and the names are discarded after that.

> I assumed getSlotValue gives you a slot reference and not an actual object handle, so there really only is the GC part to take care of.

It gives you an actual object handle. :) After you create a WrenValue, you can do whatever you want with the slot.

> I thought foreign objects would not get GC'ed?

Foreign objects can be GCd. A foreign object's memory is still managed by Wren, it's just that the *contents* of that memory are directly accessible from C so you can store data in there that is opaque to Wren. The object may still get collected. If you know to know about that happening—maybe the C data stores something like a file handle—you can register a finalizer with the class that will get called when the object is about to be collected.

I *think* that answers everything here, so I'm going to close this out. I am working on more comprehensive embedding API docs that should help clarify all of this. :)

**Comment by Banane9** [comment]
> > apart from the referenced value being able to be garbage collected.
> 
> The object referenced by a WrenValue won't be GCed until you release the WrenValue. WrenValues are persistent handles to an object so that you can ensure they're stay around as long as you need.

That's what I meant - I was saying Wren *can't* garbage collect Values pointed to by a handle :)

**Comment by munificent** [comment]
Oh, sorry, I must have read that backwards. :)

**Comment by Banane9** [comment]
I see how it can be unclear... Especially when it references something only stated in the linked API documentation ^^
