### ISSUE TITLE
Are there ready made executables?

### ISSUE THREAD

**Issue by vonHabsi** [munificent/wren#367]
Are there ready made executables?

**Comment by paulsapps** [comment]
Not official here but I don't think there are. If appveyor (like travis but for Windows) is enabled then probably published artifacts could be enabled.

**Comment by munificent** [comment]
Not currently, no. That's a good idea, though I expect it won't be worth doing until Wren is a little more mature.

Right now it's sort of a "feature" that you have to build Wren yourself because:

1. It helps flush out bugs with building and compiling Wren for various platforms.
2. It ensures the people using Wren today are comfortable getting their hands a little dirty. :)
