### ISSUE TITLE
Random numbers cross platform.

### ISSUE THREAD

**Issue by JonesAndrew** [munificent/wren#387]
You might already know this, but the random module doesn't generate the same numbers from the same seed across all platforms.
`Random.new(12345).int(0,100000)` will generate different numbers depending on the compiler's implementation of `rand()`, and there might be some benefit if the random module just used it's own random function.

**Comment by munificent** [comment]
Yeah, I was aware of that, but it didn't worry me too much. I think it's generally a bad practice to assume PRNG output is stable across machines. I wouldn't want to commit to producing stable output because that would also limit Wren's ability to tweak its RNG algorithms over time too.

Is it causing problems for you?

**Comment by JonesAndrew** [comment]
It's not really a problem, because it's easy enough to replace the functions. I just thought it would be cool for things such as cross platform replays, and lockstep multiplayer. It was causing desyncs for me, but I think you're right that the cons outweigh the pros.

**Comment by munificent** [comment]
> I just thought it would be cool for things such as cross platform replays, and lockstep multiplayer.

Yeah, there are definitely cases where a deterministic RNG is vital. You could always roll your own in those cases, though.

**Comment by JonesAndrew** [comment]
Ya, that's what I ended up doing, thanks.
