### ISSUE TITLE
Most crucial documentation (embedding) is missing

### ISSUE THREAD

**Issue by aggsol** [munificent/wren#402]
On the embedding page (http://wren.io/embedding-api.html) the most interesting parts (to me) are TODOs for quiet a while now.  Are those coming anytime soon(tm)?

**Comment by minirop** [comment]
since Bob is in the process of writing a book, I would say "probably not (soon)"? I may try to write a really short crash-course.

**Comment by Nelarius** [comment]
If you're using C++, then this [blog post](http://www.johannmuszynski.com/blog/post/embedding_wren_in_c_part_1/) that I wrote a while back may be of some use.

**Comment by munificent** [comment]
I am hoping to put some work on these before the book is done, but, yeah, I'm pretty busy these days. :)

I haven't pushed a new version of wren.io in a while because the docs are in an incomplete state, but you can see I have made some progress on them: https://github.com/munificent/wren/tree/master/doc/site/embedding

**Comment by minirop** [comment]
Nelarius' blog post explains a lot of thing, if you want something "bare", I did threw up [a few lines](http://www.wrenify.net/embed.php).

**Comment by aggsol** [comment]
@Nelarius @minirop Thank you! I will have a look and a go then
@munificent Oh, I just bookmarked the wren.io page and checked it once in while. Keep up the good work! :sparkles:
