### ISSUE TITLE
"Help Wanted" or similar label

### ISSUE THREAD

**Issue by CodogoFreddie** [munificent/wren#424]
Could we introduce an issue label marking issues where some action has been decided, and the issue is now awaiting a PR? 

Similar labels are used in some prominent Open Source projects, and are seen anecdotally as a useful thing: [redux](https://github.com/reactjs/redux/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22), [react](https://github.com/facebook/react/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+bug%22), (no prizes for guessing what I do for a living)

Contributors would then find it much easier to find useful areas for their work.

These could also be used to highlight areas of the docs that most urgently need work.

**Comment by iwillspeak** [comment]
Maybe something like Rust's [`E-Easy`](https://github.com/rust-lang/rust/issues?q=is%3Aopen+is%3Aissue+label%3AE-easy) and [`E-mentor`](https://github.com/rust-lang/rust/issues?q=is%3Aopen+is%3Aissue+label%3AE-mentor) too for marking quick fixes and issues where help is available for newbies.

**Comment by munificent** [comment]
This is a great. However, for almost entirely personal reasons, I'm going to not do this right now.

I (obviously) love open source and am very grateful for contributions. At the same time, much of the satisfaction I get from Wren is hacking on it myself. I only have a small amount of time to work on Wren these days. I find that when responding to pull requests and issues eats up all of that time, my enthusiasm for the entire project wanes, which doesn't help anyone.

So I'm hesitant to encourage more contributions than I already have because I don't seem to handle the load well. This is *not* to say that I don't appreciate everyone who wants to help. But I need to balance my time and incentives so that I don't get burned out. I hope that's OK.

**Comment by bjorn** [comment]
@munificent For what it's worth, I think you're doing a great job being open to improvements by others. It's clear that you appreciate help in pretty much any area (not the least help in making decisions), which also kinda makes the label proposed here not very useful or even deceptive.

**Comment by munificent** [comment]
Thanks, I appreciate that. 😄
