### ISSUE TITLE
Import statements can leak memory

### ISSUE THREAD

**Issue by munificent** [munificent/wren#430]
From u/sponkemonke.

Not sure where the leak is.

**Comment by minirop** [comment]
after checking with it myself, the loaded code of a module doesn't seems to be freed.

In the CLI, there is the `readModule()` function that return the malloc'd source code inside `readFile()` then pass it to the VM, but this *string* is never deleted.

I added `free((void*)source)` in [https://github.com/munificent/wren/blob/master/src/vm/wren_vm.c#L490](loadModule) line 491 (between `wrenCompile` and the `if`), now valgrind is happy. I didn't do a PR since I'm not entirely sure (but still pretty sure), and maybe you'll see something I didn't (if it's all OK for you, I'll do one)

The cast is mandatory else GCC warns that, since `free` ask for `void*` it discard the *const* modifier.

**Comment by JonesAndrew** [comment]
The problem with freeing memory there is that if you pass a string literal to `wrenInterpret` than you can't free it, or if reading a module returns a string literal like Meta and Random. Not sure what the best way to fix this because it's not really possible for the read function to free the data. Maybe add a flag that the read function can set if the source needs to be freed or not.

**Comment by folkertk1** [comment]
I may have solved this. It depends whether the munificent agrees with the way I handled it.
https://github.com/folkertk1/wren/blob/iss430/src/vm/wren_vm.c#L505 is the link to the main part of the change. I added another function called scalloc() which is exposed to the end user, however, I had to
add another variable to the vm struct to make it work

**Comment by jvidziunas** [comment]
I'm going to give a dissenting opinion here and state that the real design issue is that the import function has the 'wrong signature'/goes about the problem backwards. Instead of adding difficult to check state, why not promote the core pieces of loadModule() into the public API and have the import function return the fiber/some sort of result obtained from calling loadModule()?
