### ISSUE TITLE
use case of the language

### ISSUE THREAD

**Issue by xificurC** [munificent/wren#431]
After browsing through the sites and docs I'm not sure where to put wren - what use case are you trying to target?

I'm always looking for a bash replacement for scripting. Something with a bit more power (data structures, first-class functions, exception handling) but with the same power (running external commands (pipes, redirection, backgrounding), powerful string API (globs and regexps), simple filesystem handling (creating/filtering files/directories, reading/writing to files, ...)) and close-to-0 startup.

From a quick glance I don't see any API for starting external processses, creating directories or transforming strings with regular expressions or any other DSL. Does that mean your use case lies elsewhere?

A few more random thoughts/points:
- it would be nice to pinpoint some use cases in the README or on the web page, preferably with some examples
- the docs on wren.io are terribly broken :) The [main site](http://wren.io) has a different list on the right-hand side than [this one](http://wren.io/modules), there is no way to get [here](http://wren.io/modules/core/) from any link and some modules [don't have a page at all](http://wren.io/modules/os/)

**Comment by bjorn** [comment]
What I've read so far, is that Wren will be available as small embeddable language, as well as ship a powerful CLI application that combines Wren with all the functionality you've listed, mostly based on libuv. Of course, this serves two completely different use-cases.

But, especially since it is still mainly a one-man side project, it will take a long time to get there and currently if you want to use Wren, you have to be prepared to help fill in the blanks for any stuff you're missing.

**Comment by minirop** [comment]
Bob: « I’m an ex-game developer, so when I think “scripting”, I tend to think “game scripting”. » [source](http://wren.io/qa.html)

> The main site has a different list on the right-hand side than this one
IIRC the right-hand side of the module page is the old menu. Maybe it didn't get regenerated if it hadn't changed since?

> there is no way to get here from any link
on the module page, bottom of the menu

> and some modules don't have a page at all
OS is a CLI only module, the docs only lists built-in modules (there is only "core")

**Comment by munificent** [comment]
Oof, yeah, I must have left some stale files around the last time I regenerated it. Once I get the embedding docs done, I'll blow it away and get it cleaned up.

**Comment by munificent** [comment]
Docs have been regenerated and auto-deploy whenever a change lands on master.
