### ISSUE TITLE
Fiber.try() doesn't catch bubbling exceptions

### ISSUE THREAD

**Issue by JonesAndrew** [munificent/wren#434]
```dart
var a = Fiber.new {
    var b = Fiber.new {
        var a  = "4"
        var b = 4
        a + b
    }
    b.call()
}
a.try()
```

My understanding that using `try()` with `a` will cause this program to finish successfully. However, locally I get `Right operand must be a string. [main line 5] in new(_) block argument`. My assumption of how `try()` works might also just be wrong.

**Comment by munificent** [comment]
Yeah, I think your assumption is right too. I say "think" because using a chain of called coroutines for exception handling is kind of unusual, so I and all of us are still kind of figuring out how it should work. :)

But it was definitely my *intent* that all of the fibers along a path of calls would unwind when a runtime error occurs, not just the first. I tweaked your fix a bit but overall it was great. Thank you!
