### ISSUE TITLE
Feature: import/include/require code?

### ISSUE THREAD

**Issue by pwoolcoc** [munificent/wren#46]
Did you plan on including some mechanism to import/include/require code in Wren? Or is all code outside of `core`/`io`supposed to be provided by the host application?

**Comment by munificent** [comment]
Yes and yes.

I need some sort of import mechanism, but the host application will have control over how the contents of the imported "module" thing are physically located.

I've put a little thought into this but I want to wait until there's a bit more Wren code in the wild (or at least that I've written) so I can get a better sense of how it feels to use with a real program.

**Comment by EvanHahn** [comment]
Personally, I'd like to see an explicit "these are the objects that are exported" declaration rather than have everything public by default. My opinion, of course!

**Comment by joshhartigan** [comment]
how about a 'module exports' array, a la node's `module.exports` object?

**Comment by ryanplusplus** [comment]
I've always thought Lua handled this pretty well.  In Lua whatever you return is exported, so you can simply return a table and that will be equivalent to <code>module.exports</code>.  This removes the need for a 'magic' object.

**Comment by joshhartigan** [comment]
:+1: for that idea

**Comment by munificent** [comment]
Wren doesn't have tables, so the natural thing to return would be an object, but, yes, I've been thinking about something similar to what Lua does. A couple of tricky parts are figuring out how best to handle shared imports (you import a and b which both import c) and potentially cyclic imports.

I've been doing a lot of thinking here and have some rough notes. I'll try to put something together relatively soon with my idea(s). I *definitely* want to keep it simple, but I'm hoping to do something a little better than treating an import like a textual file include and dumping everything into a single global state.

**Comment by ryanplusplus** [comment]
In Node.js and Lua, shared imports are not a problem because imports do not affect the global (or even local) environment directly.  Instead, all imports have to be stored in a variable that acts as a sort of namespace for the exports.

Using this strategy allows you to sidestep a lot of problems with imports.

**Comment by munificent** [comment]
Yeah, I'm leaning towards that too. That solves some of the scoping problems, but not all of them. I need to spend some time gathering and writing down my thoughts here. It's not quite as easy in Wren as it might be in some other languages because of Wren's own constraints. In particular:

1. I want to keep it with a single-pass compiler.
2. But I want to report undefined variable errors at compile time.
3. And I'd like to support cyclic imports.

The last point may seem contentious, but statically typed languages generally don't have any problems with cyclic references between modules. That's important because it's entirely common for two modules to each have *type annotations* that refer to names defined in the other module.

Wren, of course, is dynamically typed, but I'm interested in having a separate static analysis tool for it to catch type errors. In that case, it would be nice if we had a good syntax for type annotations and if those names could be resolved correctly.

That means I'd like to not rule out cyclic imports if possible. But supporting them while keeping the module system very simple is pretty hard.

**Comment by munificent** [comment]
I wrote up a strawman. I'm not sure the best way to discuss proposals like this so, for kicks, I thought I'd try doing it in the issue tracker. I didn't want to post it here since it's super long (and there may be other separate module proposals so solve this bug), so it's here: #79.

Comment away!

**Comment by peterlada** [comment]
WEP-0: Wren Enhancement Proposal :)
Could start at 0, community likes that better than 1?

**Comment by munificent** [comment]
I think we'll have to wait for a slightly more official proposal process before we start numbering them. :)

**Comment by pwoolcoc** [comment]
@peterlada Isn't the philosophy, "when in doubt, do what lua does?" So they should start at 1 :)

**Comment by munificent** [comment]
I'm not in doubt that starting at zero is the right answer! :D

**Comment by zeckalpha** [comment]
Should imports only be allowed top level or allowed inside classes and methods?

**Comment by munificent** [comment]
Modules have landed in master!

**Comment by MarcoLizza** [comment]
Horray! :party:

**Comment by pwoolcoc** [comment]
:+1:

**Comment by munificent** [comment]
@zeckalpha, import statements are allowed anywhere a variable can be declared, including inside methods and functions.
