### ISSUE TITLE
Reconsider having both .. and ... for ranges?

### ISSUE THREAD

**Issue by skybrian** [munificent/wren#53]
The .. and ... operators seem confusingly similar. I know Ruby does this, but is it a good idea to copy it? 

But I'm not sure what to suggest. Perhaps 1 ..< 5 for a half-open range? Or perhaps having both isn't actually necessary?

(This is just a bit of ignorable bikeshedding. Otherwise, I find Wren rather tasteful.)

**Comment by munificent** [comment]
I think having both exclusive and inclusive ranges is really important, especially when you consider things like slicing lists and ranges that are used to enumerate the indices in a list.

I really like the way `..` and `...` look, but I admit their interpretation isn't at all obvious. I actually wish Ruby interpreted them the other way, where `...` was inclusive (because it has one more dot, hence one more item in the range) but I thought I'd lean on prior art here.

I find `1..<5` pretty ugly. :(

Maybe see if you get used to what it currently has? If not, nothing is carved in stone. I'll close this for now, but keep bugging me if this keeps bugging you. :)
