### ISSUE TITLE
Anonymous classes?

### ISSUE THREAD

**Issue by IngwiePhoenix** [munificent/wren#628]
A question of curiosity: If I were to write an event handler, I could either use block arguments - or I could use anonymous classes.

```
event.set class {
  onA() {...}
  onB() {...}
}
```

Something like the above would be nice to have, as using maps for that looks a little bit weird due to all the quotes - it just feels like mis-typed JSON :)

```
{
  "onA": {...},
  "onB": {...}
}
```

So would anonymous classes be possible in order to pass more complex structured arguments?

**Comment by mhermier** [comment]
Le dim. 11 nov. 2018 à 11:44, Ingwie Phoenix <notifications@github.com> a
écrit :

> A question of curiosity: If I were to write an event handler, I could
> either use block arguments - or I could use anonymous classes.
>
> event.set class {
>   onA() {...}
>   onB() {...}
> }
>
> Parenthesis removal does not seems desirable in that case. The compiler
will not allow it as this, and I don't think it is a valuable syntaxic
sugar.

>  Something like the above would be nice to have, as using maps for that
> looks a little bit weird due to all the quotes - it just feels like
> mis-typed JSON :)
>
> {
>   "onA": {...},
>   "onB": {...}
> }
>
> There should be a Fun.new in front on the methods also.

>  So would anonymous classes be possible in order to pass more complex
> structured arguments?
>
Short answer yes. Since the language is untyped you can always pass
anything that has the correct interface. But if you need to check for
methods, for now in the collee, there is only 'Fiber.try'  unfortunately.

>

**Comment by IngwiePhoenix** [comment]
I see. Looks like I will have to go with other ideas then. Thank you for the reply. :)
