### ISSUE TITLE
Implement a Wren parser in Wren

### ISSUE THREAD

**Issue by zeckalpha** [munificent/wren#88]
This wouldn't necessarily be for a single-pass bytecode emitter like the existing parser. I'm not suggesting replacing it by bootstrapping Wren. Instead, I'm suggesting a parser to construct ASTs. This could be useful for iterating on the grammar, and a few other projects I'd like to tackle, to be mentioned in subsequent issues.

**Comment by munificent** [comment]
I have started toying with this a while back, but didn't put much time into it. I agree it wouldn't be used in the Wren implementation itself, but I'm hoping to eventually have a static analysis too written in Wren. Having a reusable parser in Wren would be swell.

**Comment by munificent** [comment]
I took the lexer I started and tossed it up here: https://gist.github.com/munificent/8b5c2240e7364913b6a6

Since I've got plenty of other stuff to work on, if you want to take that and run with it, be my guest. I didn't create an actual repo for it so that you (or anyone else) can just claim it and that way I'm not the bottleneck for merging in changes.

**Comment by zeckalpha** [comment]
Nice!

**Comment by munificent** [comment]
This is not at all *done*, but now that there is a repo for [wrenalyzer](https://github.com/munificent/wrenalyzer), we can track this there.
